// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: model_router_installations.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

const addModelRouterInstallationExcludedModel = `-- name: AddModelRouterInstallationExcludedModel :execrows

UPDATE router.model_router_installations
SET excluded_models = array_append(ARRAY(SELECT v FROM unnest(excluded_models) WITH ORDINALITY AS t(v, ord) WHERE v = ANY($1::text[]) ORDER BY ord), $2::text),
    updated_at = NOW()
WHERE id = $3::uuid
  AND external_id = $4::varchar
  AND deleted_at IS NULL
  AND NOT ($2::text = ANY(excluded_models))
  AND (NOT $5::boolean OR EXISTS (
    SELECT 1 FROM unnest($6::text[]) WITH ORDINALITY AS um(model, i)
    JOIN unnest($7::text[]) WITH ORDINALITY AS up(provider, i) ON up.i = um.i
    WHERE um.model <> $2::text
      AND NOT (um.model = ANY(excluded_models))
      AND NOT (up.provider = ANY(excluded_providers))
  ))
`

type AddModelRouterInstallationExcludedModelParams struct {
	Keep              []string
	Item              string
	ID                uuid.UUID
	ExternalID        string
	GuardRoutable     bool
	UniverseModels    []string
	UniverseProviders []string
}

// Per-item edits of the model-selection lists. Each is one conditional UPDATE,
// so concurrent edits of the same list cannot lose one another. Stored entries
// outside @keep (stale ids no longer selectable) are dropped in the same write.
// An add lands only when the item is absent and a remove only when it is
// present; 0 rows otherwise, when not found, or when an exclusion add fails the
// guard_routable check described on UpdateModelRouterInstallationExcludedModels.
//
//	UPDATE router.model_router_installations
//	SET excluded_models = array_append(ARRAY(SELECT v FROM unnest(excluded_models) WITH ORDINALITY AS t(v, ord) WHERE v = ANY($1::text[]) ORDER BY ord), $2::text),
//	    updated_at = NOW()
//	WHERE id = $3::uuid
//	  AND external_id = $4::varchar
//	  AND deleted_at IS NULL
//	  AND NOT ($2::text = ANY(excluded_models))
//	  AND (NOT $5::boolean OR EXISTS (
//	    SELECT 1 FROM unnest($6::text[]) WITH ORDINALITY AS um(model, i)
//	    JOIN unnest($7::text[]) WITH ORDINALITY AS up(provider, i) ON up.i = um.i
//	    WHERE um.model <> $2::text
//	      AND NOT (um.model = ANY(excluded_models))
//	      AND NOT (up.provider = ANY(excluded_providers))
//	  ))
func (q *Queries) AddModelRouterInstallationExcludedModel(ctx context.Context, arg AddModelRouterInstallationExcludedModelParams) (int64, error) {
	result, err := q.db.Exec(ctx, addModelRouterInstallationExcludedModel,
		arg.Keep,
		arg.Item,
		arg.ID,
		arg.ExternalID,
		arg.GuardRoutable,
		arg.UniverseModels,
		arg.UniverseProviders,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const addModelRouterInstallationExcludedProvider = `-- name: AddModelRouterInstallationExcludedProvider :execrows
UPDATE router.model_router_installations
SET excluded_providers = array_append(ARRAY(SELECT v FROM unnest(excluded_providers) WITH ORDINALITY AS t(v, ord) WHERE v = ANY($1::text[]) ORDER BY ord), $2::text),
    updated_at = NOW()
WHERE id = $3::uuid
  AND external_id = $4::varchar
  AND deleted_at IS NULL
  AND NOT ($2::text = ANY(excluded_providers))
  AND (NOT $5::boolean OR EXISTS (
    SELECT 1 FROM unnest($6::text[]) WITH ORDINALITY AS um(model, i)
    JOIN unnest($7::text[]) WITH ORDINALITY AS up(provider, i) ON up.i = um.i
    WHERE up.provider <> $2::text
      AND NOT (um.model = ANY(excluded_models))
      AND NOT (up.provider = ANY(excluded_providers))
  ))
`

type AddModelRouterInstallationExcludedProviderParams struct {
	Keep              []string
	Item              string
	ID                uuid.UUID
	ExternalID        string
	GuardRoutable     bool
	UniverseModels    []string
	UniverseProviders []string
}

// AddModelRouterInstallationExcludedProvider
//
//	UPDATE router.model_router_installations
//	SET excluded_providers = array_append(ARRAY(SELECT v FROM unnest(excluded_providers) WITH ORDINALITY AS t(v, ord) WHERE v = ANY($1::text[]) ORDER BY ord), $2::text),
//	    updated_at = NOW()
//	WHERE id = $3::uuid
//	  AND external_id = $4::varchar
//	  AND deleted_at IS NULL
//	  AND NOT ($2::text = ANY(excluded_providers))
//	  AND (NOT $5::boolean OR EXISTS (
//	    SELECT 1 FROM unnest($6::text[]) WITH ORDINALITY AS um(model, i)
//	    JOIN unnest($7::text[]) WITH ORDINALITY AS up(provider, i) ON up.i = um.i
//	    WHERE up.provider <> $2::text
//	      AND NOT (um.model = ANY(excluded_models))
//	      AND NOT (up.provider = ANY(excluded_providers))
//	  ))
func (q *Queries) AddModelRouterInstallationExcludedProvider(ctx context.Context, arg AddModelRouterInstallationExcludedProviderParams) (int64, error) {
	result, err := q.db.Exec(ctx, addModelRouterInstallationExcludedProvider,
		arg.Keep,
		arg.Item,
		arg.ID,
		arg.ExternalID,
		arg.GuardRoutable,
		arg.UniverseModels,
		arg.UniverseProviders,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const addModelRouterInstallationPreferredModel = `-- name: AddModelRouterInstallationPreferredModel :execrows
UPDATE router.model_router_installations
SET preferred_models = array_append(ARRAY(SELECT v FROM unnest(preferred_models) WITH ORDINALITY AS t(v, ord) WHERE v = ANY($1::text[]) ORDER BY ord), $2::text),
    updated_at = NOW()
WHERE id = $3::uuid
  AND external_id = $4::varchar
  AND deleted_at IS NULL
  AND NOT ($2::text = ANY(preferred_models))
`

type AddModelRouterInstallationPreferredModelParams struct {
	Keep       []string
	Item       string
	ID         uuid.UUID
	ExternalID string
}

// AddModelRouterInstallationPreferredModel
//
//	UPDATE router.model_router_installations
//	SET preferred_models = array_append(ARRAY(SELECT v FROM unnest(preferred_models) WITH ORDINALITY AS t(v, ord) WHERE v = ANY($1::text[]) ORDER BY ord), $2::text),
//	    updated_at = NOW()
//	WHERE id = $3::uuid
//	  AND external_id = $4::varchar
//	  AND deleted_at IS NULL
//	  AND NOT ($2::text = ANY(preferred_models))
func (q *Queries) AddModelRouterInstallationPreferredModel(ctx context.Context, arg AddModelRouterInstallationPreferredModelParams) (int64, error) {
	result, err := q.db.Exec(ctx, addModelRouterInstallationPreferredModel,
		arg.Keep,
		arg.Item,
		arg.ID,
		arg.ExternalID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const createModelRouterInstallation = `-- name: CreateModelRouterInstallation :one
INSERT INTO router.model_router_installations (
    external_id,
    name,
    created_by
)
VALUES (
    $1::varchar,
    $2::varchar,
    $3
)
RETURNING id, external_id, name, created_at, updated_at, deleted_at, created_by, excluded_models, excluded_providers, routing_quality_weight, usage_bypass_enabled, usage_bypass_threshold, preferred_models, subscription_routing_disabled, routing_strategy, routing_rollout_id, policy_shadow_strategy, policy_debug_enabled, policy_header_overrides_enabled, policy_routing_intent, ai_training_allowed, byok_enabled, content_capture_mode, hide_terminal_surfaces, allowed_models, first_request_served_at, flag_overrides, models_when_subscription_active, models_when_subscription_inactive, fast_mode_models, trial_capture_enabled, trial_enrollment_id, trial_shadow_sample_rate, trial_shadow_daily_ceiling_usd_micros, show_model_selection_reasoning, subscription_sharing_enabled
`

type CreateModelRouterInstallationParams struct {
	ExternalID string
	Name       string
	CreatedBy  *string
}

// CreateModelRouterInstallation
//
//	INSERT INTO router.model_router_installations (
//	    external_id,
//	    name,
//	    created_by
//	)
//	VALUES (
//	    $1::varchar,
//	    $2::varchar,
//	    $3
//	)
//	RETURNING id, external_id, name, created_at, updated_at, deleted_at, created_by, excluded_models, excluded_providers, routing_quality_weight, usage_bypass_enabled, usage_bypass_threshold, preferred_models, subscription_routing_disabled, routing_strategy, routing_rollout_id, policy_shadow_strategy, policy_debug_enabled, policy_header_overrides_enabled, policy_routing_intent, ai_training_allowed, byok_enabled, content_capture_mode, hide_terminal_surfaces, allowed_models, first_request_served_at, flag_overrides, models_when_subscription_active, models_when_subscription_inactive, fast_mode_models, trial_capture_enabled, trial_enrollment_id, trial_shadow_sample_rate, trial_shadow_daily_ceiling_usd_micros, show_model_selection_reasoning, subscription_sharing_enabled
func (q *Queries) CreateModelRouterInstallation(ctx context.Context, arg CreateModelRouterInstallationParams) (RouterModelRouterInstallation, error) {
	row := q.db.QueryRow(ctx, createModelRouterInstallation, arg.ExternalID, arg.Name, arg.CreatedBy)
	var i RouterModelRouterInstallation
	err := row.Scan(
		&i.ID,
		&i.ExternalID,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.CreatedBy,
		&i.ExcludedModels,
		&i.ExcludedProviders,
		&i.RoutingQualityWeight,
		&i.UsageBypassEnabled,
		&i.UsageBypassThreshold,
		&i.PreferredModels,
		&i.SubscriptionRoutingDisabled,
		&i.RoutingStrategy,
		&i.RoutingRolloutID,
		&i.PolicyShadowStrategy,
		&i.PolicyDebugEnabled,
		&i.PolicyHeaderOverridesEnabled,
		&i.PolicyRoutingIntent,
		&i.AiTrainingAllowed,
		&i.ByokEnabled,
		&i.ContentCaptureMode,
		&i.HideTerminalSurfaces,
		&i.AllowedModels,
		&i.FirstRequestServedAt,
		&i.FlagOverrides,
		&i.ModelsWhenSubscriptionActive,
		&i.ModelsWhenSubscriptionInactive,
		&i.FastModeModels,
		&i.TrialCaptureEnabled,
		&i.TrialEnrollmentID,
		&i.TrialShadowSampleRate,
		&i.TrialShadowDailyCeilingUsdMicros,
		&i.ShowModelSelectionReasoning,
		&i.SubscriptionSharingEnabled,
	)
	return i, err
}

const getModelRouterInstallation = `-- name: GetModelRouterInstallation :one
SELECT id, external_id, name, created_at, updated_at, deleted_at, created_by, excluded_models, excluded_providers, routing_quality_weight, usage_bypass_enabled, usage_bypass_threshold, preferred_models, subscription_routing_disabled, routing_strategy, routing_rollout_id, policy_shadow_strategy, policy_debug_enabled, policy_header_overrides_enabled, policy_routing_intent, ai_training_allowed, byok_enabled, content_capture_mode, hide_terminal_surfaces, allowed_models, first_request_served_at, flag_overrides, models_when_subscription_active, models_when_subscription_inactive, fast_mode_models, trial_capture_enabled, trial_enrollment_id, trial_shadow_sample_rate, trial_shadow_daily_ceiling_usd_micros, show_model_selection_reasoning, subscription_sharing_enabled
FROM router.model_router_installations
WHERE id = $1::uuid
  AND external_id = $2::varchar
  AND deleted_at IS NULL
`

type GetModelRouterInstallationParams struct {
	ID         uuid.UUID
	ExternalID string
}

// Gets an installation by id, scoped to an external_id to prevent cross-tenant access.
//
//	SELECT id, external_id, name, created_at, updated_at, deleted_at, created_by, excluded_models, excluded_providers, routing_quality_weight, usage_bypass_enabled, usage_bypass_threshold, preferred_models, subscription_routing_disabled, routing_strategy, routing_rollout_id, policy_shadow_strategy, policy_debug_enabled, policy_header_overrides_enabled, policy_routing_intent, ai_training_allowed, byok_enabled, content_capture_mode, hide_terminal_surfaces, allowed_models, first_request_served_at, flag_overrides, models_when_subscription_active, models_when_subscription_inactive, fast_mode_models, trial_capture_enabled, trial_enrollment_id, trial_shadow_sample_rate, trial_shadow_daily_ceiling_usd_micros, show_model_selection_reasoning, subscription_sharing_enabled
//	FROM router.model_router_installations
//	WHERE id = $1::uuid
//	  AND external_id = $2::varchar
//	  AND deleted_at IS NULL
func (q *Queries) GetModelRouterInstallation(ctx context.Context, arg GetModelRouterInstallationParams) (RouterModelRouterInstallation, error) {
	row := q.db.QueryRow(ctx, getModelRouterInstallation, arg.ID, arg.ExternalID)
	var i RouterModelRouterInstallation
	err := row.Scan(
		&i.ID,
		&i.ExternalID,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.CreatedBy,
		&i.ExcludedModels,
		&i.ExcludedProviders,
		&i.RoutingQualityWeight,
		&i.UsageBypassEnabled,
		&i.UsageBypassThreshold,
		&i.PreferredModels,
		&i.SubscriptionRoutingDisabled,
		&i.RoutingStrategy,
		&i.RoutingRolloutID,
		&i.PolicyShadowStrategy,
		&i.PolicyDebugEnabled,
		&i.PolicyHeaderOverridesEnabled,
		&i.PolicyRoutingIntent,
		&i.AiTrainingAllowed,
		&i.ByokEnabled,
		&i.ContentCaptureMode,
		&i.HideTerminalSurfaces,
		&i.AllowedModels,
		&i.FirstRequestServedAt,
		&i.FlagOverrides,
		&i.ModelsWhenSubscriptionActive,
		&i.ModelsWhenSubscriptionInactive,
		&i.FastModeModels,
		&i.TrialCaptureEnabled,
		&i.TrialEnrollmentID,
		&i.TrialShadowSampleRate,
		&i.TrialShadowDailyCeilingUsdMicros,
		&i.ShowModelSelectionReasoning,
		&i.SubscriptionSharingEnabled,
	)
	return i, err
}

const listModelRouterInstallationsForExternalID = `-- name: ListModelRouterInstallationsForExternalID :many
SELECT id, external_id, name, created_at, updated_at, deleted_at, created_by, excluded_models, excluded_providers, routing_quality_weight, usage_bypass_enabled, usage_bypass_threshold, preferred_models, subscription_routing_disabled, routing_strategy, routing_rollout_id, policy_shadow_strategy, policy_debug_enabled, policy_header_overrides_enabled, policy_routing_intent, ai_training_allowed, byok_enabled, content_capture_mode, hide_terminal_surfaces, allowed_models, first_request_served_at, flag_overrides, models_when_subscription_active, models_when_subscription_inactive, fast_mode_models, trial_capture_enabled, trial_enrollment_id, trial_shadow_sample_rate, trial_shadow_daily_ceiling_usd_micros, show_model_selection_reasoning, subscription_sharing_enabled
FROM router.model_router_installations
WHERE external_id = $1::varchar
  AND deleted_at IS NULL
ORDER BY created_at DESC
`

// ListModelRouterInstallationsForExternalID
//
//	SELECT id, external_id, name, created_at, updated_at, deleted_at, created_by, excluded_models, excluded_providers, routing_quality_weight, usage_bypass_enabled, usage_bypass_threshold, preferred_models, subscription_routing_disabled, routing_strategy, routing_rollout_id, policy_shadow_strategy, policy_debug_enabled, policy_header_overrides_enabled, policy_routing_intent, ai_training_allowed, byok_enabled, content_capture_mode, hide_terminal_surfaces, allowed_models, first_request_served_at, flag_overrides, models_when_subscription_active, models_when_subscription_inactive, fast_mode_models, trial_capture_enabled, trial_enrollment_id, trial_shadow_sample_rate, trial_shadow_daily_ceiling_usd_micros, show_model_selection_reasoning, subscription_sharing_enabled
//	FROM router.model_router_installations
//	WHERE external_id = $1::varchar
//	  AND deleted_at IS NULL
//	ORDER BY created_at DESC
func (q *Queries) ListModelRouterInstallationsForExternalID(ctx context.Context, externalID string) ([]RouterModelRouterInstallation, error) {
	rows, err := q.db.Query(ctx, listModelRouterInstallationsForExternalID, externalID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RouterModelRouterInstallation
	for rows.Next() {
		var i RouterModelRouterInstallation
		if err := rows.Scan(
			&i.ID,
			&i.ExternalID,
			&i.Name,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.CreatedBy,
			&i.ExcludedModels,
			&i.ExcludedProviders,
			&i.RoutingQualityWeight,
			&i.UsageBypassEnabled,
			&i.UsageBypassThreshold,
			&i.PreferredModels,
			&i.SubscriptionRoutingDisabled,
			&i.RoutingStrategy,
			&i.RoutingRolloutID,
			&i.PolicyShadowStrategy,
			&i.PolicyDebugEnabled,
			&i.PolicyHeaderOverridesEnabled,
			&i.PolicyRoutingIntent,
			&i.AiTrainingAllowed,
			&i.ByokEnabled,
			&i.ContentCaptureMode,
			&i.HideTerminalSurfaces,
			&i.AllowedModels,
			&i.FirstRequestServedAt,
			&i.FlagOverrides,
			&i.ModelsWhenSubscriptionActive,
			&i.ModelsWhenSubscriptionInactive,
			&i.FastModeModels,
			&i.TrialCaptureEnabled,
			&i.TrialEnrollmentID,
			&i.TrialShadowSampleRate,
			&i.TrialShadowDailyCeilingUsdMicros,
			&i.ShowModelSelectionReasoning,
			&i.SubscriptionSharingEnabled,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markModelRouterInstallationFirstRequestServed = `-- name: MarkModelRouterInstallationFirstRequestServed :exec
UPDATE router.model_router_installations
SET first_request_served_at = NOW()
WHERE id = $1::uuid
  AND deleted_at IS NULL
  AND first_request_served_at IS NULL
`

// Stamps first_request_served_at the first time this installation routes a
// request. WHERE IS NULL makes the update a no-op after the first write, so
// the timestamp records the *first* request and rotation never resets it.
//
//	UPDATE router.model_router_installations
//	SET first_request_served_at = NOW()
//	WHERE id = $1::uuid
//	  AND deleted_at IS NULL
//	  AND first_request_served_at IS NULL
func (q *Queries) MarkModelRouterInstallationFirstRequestServed(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, markModelRouterInstallationFirstRequestServed, id)
	return err
}

const removeModelRouterInstallationExcludedModel = `-- name: RemoveModelRouterInstallationExcludedModel :execrows
UPDATE router.model_router_installations
SET excluded_models = array_remove(ARRAY(SELECT v FROM unnest(excluded_models) WITH ORDINALITY AS t(v, ord) WHERE v = ANY($1::text[]) ORDER BY ord), $2::text),
    updated_at = NOW()
WHERE id = $3::uuid
  AND external_id = $4::varchar
  AND deleted_at IS NULL
  AND $2::text = ANY(excluded_models)
`

type RemoveModelRouterInstallationExcludedModelParams struct {
	Keep       []string
	Item       string
	ID         uuid.UUID
	ExternalID string
}

// RemoveModelRouterInstallationExcludedModel
//
//	UPDATE router.model_router_installations
//	SET excluded_models = array_remove(ARRAY(SELECT v FROM unnest(excluded_models) WITH ORDINALITY AS t(v, ord) WHERE v = ANY($1::text[]) ORDER BY ord), $2::text),
//	    updated_at = NOW()
//	WHERE id = $3::uuid
//	  AND external_id = $4::varchar
//	  AND deleted_at IS NULL
//	  AND $2::text = ANY(excluded_models)
func (q *Queries) RemoveModelRouterInstallationExcludedModel(ctx context.Context, arg RemoveModelRouterInstallationExcludedModelParams) (int64, error) {
	result, err := q.db.Exec(ctx, removeModelRouterInstallationExcludedModel,
		arg.Keep,
		arg.Item,
		arg.ID,
		arg.ExternalID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const removeModelRouterInstallationExcludedProvider = `-- name: RemoveModelRouterInstallationExcludedProvider :execrows
UPDATE router.model_router_installations
SET excluded_providers = array_remove(ARRAY(SELECT v FROM unnest(excluded_providers) WITH ORDINALITY AS t(v, ord) WHERE v = ANY($1::text[]) ORDER BY ord), $2::text),
    updated_at = NOW()
WHERE id = $3::uuid
  AND external_id = $4::varchar
  AND deleted_at IS NULL
  AND $2::text = ANY(excluded_providers)
`

type RemoveModelRouterInstallationExcludedProviderParams struct {
	Keep       []string
	Item       string
	ID         uuid.UUID
	ExternalID string
}

// RemoveModelRouterInstallationExcludedProvider
//
//	UPDATE router.model_router_installations
//	SET excluded_providers = array_remove(ARRAY(SELECT v FROM unnest(excluded_providers) WITH ORDINALITY AS t(v, ord) WHERE v = ANY($1::text[]) ORDER BY ord), $2::text),
//	    updated_at = NOW()
//	WHERE id = $3::uuid
//	  AND external_id = $4::varchar
//	  AND deleted_at IS NULL
//	  AND $2::text = ANY(excluded_providers)
func (q *Queries) RemoveModelRouterInstallationExcludedProvider(ctx context.Context, arg RemoveModelRouterInstallationExcludedProviderParams) (int64, error) {
	result, err := q.db.Exec(ctx, removeModelRouterInstallationExcludedProvider,
		arg.Keep,
		arg.Item,
		arg.ID,
		arg.ExternalID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const removeModelRouterInstallationPreferredModel = `-- name: RemoveModelRouterInstallationPreferredModel :execrows
UPDATE router.model_router_installations
SET preferred_models = array_remove(ARRAY(SELECT v FROM unnest(preferred_models) WITH ORDINALITY AS t(v, ord) WHERE v = ANY($1::text[]) ORDER BY ord), $2::text),
    updated_at = NOW()
WHERE id = $3::uuid
  AND external_id = $4::varchar
  AND deleted_at IS NULL
  AND $2::text = ANY(preferred_models)
`

type RemoveModelRouterInstallationPreferredModelParams struct {
	Keep       []string
	Item       string
	ID         uuid.UUID
	ExternalID string
}

// RemoveModelRouterInstallationPreferredModel
//
//	UPDATE router.model_router_installations
//	SET preferred_models = array_remove(ARRAY(SELECT v FROM unnest(preferred_models) WITH ORDINALITY AS t(v, ord) WHERE v = ANY($1::text[]) ORDER BY ord), $2::text),
//	    updated_at = NOW()
//	WHERE id = $3::uuid
//	  AND external_id = $4::varchar
//	  AND deleted_at IS NULL
//	  AND $2::text = ANY(preferred_models)
func (q *Queries) RemoveModelRouterInstallationPreferredModel(ctx context.Context, arg RemoveModelRouterInstallationPreferredModelParams) (int64, error) {
	result, err := q.db.Exec(ctx, removeModelRouterInstallationPreferredModel,
		arg.Keep,
		arg.Item,
		arg.ID,
		arg.ExternalID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const softDeleteModelRouterInstallation = `-- name: SoftDeleteModelRouterInstallation :exec
UPDATE router.model_router_installations
SET deleted_at = NOW()
WHERE id = $1::uuid
  AND external_id = $2::varchar
  AND deleted_at IS NULL
`

type SoftDeleteModelRouterInstallationParams struct {
	ID         uuid.UUID
	ExternalID string
}

// Soft-deletes an installation, scoped to an external_id to prevent cross-tenant deletes.
//
//	UPDATE router.model_router_installations
//	SET deleted_at = NOW()
//	WHERE id = $1::uuid
//	  AND external_id = $2::varchar
//	  AND deleted_at IS NULL
func (q *Queries) SoftDeleteModelRouterInstallation(ctx context.Context, arg SoftDeleteModelRouterInstallationParams) error {
	_, err := q.db.Exec(ctx, softDeleteModelRouterInstallation, arg.ID, arg.ExternalID)
	return err
}

const updateModelRouterInstallationAllowedModels = `-- name: UpdateModelRouterInstallationAllowedModels :execrows
UPDATE router.model_router_installations
SET allowed_models = $1::text[],
    updated_at = NOW()
WHERE id = $2::uuid
  AND external_id = $3::varchar
  AND deleted_at IS NULL
`

type UpdateModelRouterInstallationAllowedModelsParams struct {
	AllowedModels []string
	ID            uuid.UUID
	ExternalID    string
}

// Replaces the per-installation positive model allowlist, scoped to an
// external_id to prevent cross-tenant updates. Empty array means "no
// restriction" (all models routable), NOT "no models". Bumps updated_at so
// dashboards see the change.
//
//	UPDATE router.model_router_installations
//	SET allowed_models = $1::text[],
//	    updated_at = NOW()
//	WHERE id = $2::uuid
//	  AND external_id = $3::varchar
//	  AND deleted_at IS NULL
func (q *Queries) UpdateModelRouterInstallationAllowedModels(ctx context.Context, arg UpdateModelRouterInstallationAllowedModelsParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateModelRouterInstallationAllowedModels, arg.AllowedModels, arg.ID, arg.ExternalID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateModelRouterInstallationContentCaptureMode = `-- name: UpdateModelRouterInstallationContentCaptureMode :execrows
UPDATE router.model_router_installations
SET content_capture_mode = $1,
    updated_at = NOW()
WHERE id = $2::uuid
  AND external_id = $3::varchar
  AND deleted_at IS NULL
`

type UpdateModelRouterInstallationContentCaptureModeParams struct {
	ContentCaptureMode *string
	ID                 uuid.UUID
	ExternalID         string
}

// Sets the per-installation capture ceiling ('off', 'hashed', or 'full'), scoped
// to an external_id to prevent cross-tenant updates. NULL clears the override.
//
//	UPDATE router.model_router_installations
//	SET content_capture_mode = $1,
//	    updated_at = NOW()
//	WHERE id = $2::uuid
//	  AND external_id = $3::varchar
//	  AND deleted_at IS NULL
func (q *Queries) UpdateModelRouterInstallationContentCaptureMode(ctx context.Context, arg UpdateModelRouterInstallationContentCaptureModeParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateModelRouterInstallationContentCaptureMode, arg.ContentCaptureMode, arg.ID, arg.ExternalID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateModelRouterInstallationExcludedModels = `-- name: UpdateModelRouterInstallationExcludedModels :execrows
UPDATE router.model_router_installations
SET excluded_models = $1::text[],
    updated_at = NOW()
WHERE id = $2::uuid
  AND external_id = $3::varchar
  AND deleted_at IS NULL
  AND (NOT $4::boolean OR EXISTS (
    SELECT 1 FROM unnest($5::text[]) WITH ORDINALITY AS um(model, i)
    JOIN unnest($6::text[]) WITH ORDINALITY AS up(provider, i) ON up.i = um.i
    WHERE NOT (um.model = ANY($1::text[]))
      AND NOT (up.provider = ANY(excluded_providers))
  ))
`

type UpdateModelRouterInstallationExcludedModelsParams struct {
	ExcludedModels    []string
	ID                uuid.UUID
	ExternalID        string
	GuardRoutable     bool
	UniverseModels    []string
	UniverseProviders []string
}

// Replaces the per-installation model exclusion list, scoped to an external_id
// to prevent cross-tenant updates. Empty array means "no exclusion". Bumps
// updated_at so dashboards see the change. With guard_routable, the write only
// lands when some universe model stays enabled with its provider not excluded,
// checked in the same statement so a concurrent provider edit cannot race it;
// 0 rows then means "would leave nothing routable" or "not found".
//
//	UPDATE router.model_router_installations
//	SET excluded_models = $1::text[],
//	    updated_at = NOW()
//	WHERE id = $2::uuid
//	  AND external_id = $3::varchar
//	  AND deleted_at IS NULL
//	  AND (NOT $4::boolean OR EXISTS (
//	    SELECT 1 FROM unnest($5::text[]) WITH ORDINALITY AS um(model, i)
//	    JOIN unnest($6::text[]) WITH ORDINALITY AS up(provider, i) ON up.i = um.i
//	    WHERE NOT (um.model = ANY($1::text[]))
//	      AND NOT (up.provider = ANY(excluded_providers))
//	  ))
func (q *Queries) UpdateModelRouterInstallationExcludedModels(ctx context.Context, arg UpdateModelRouterInstallationExcludedModelsParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateModelRouterInstallationExcludedModels,
		arg.ExcludedModels,
		arg.ID,
		arg.ExternalID,
		arg.GuardRoutable,
		arg.UniverseModels,
		arg.UniverseProviders,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateModelRouterInstallationExcludedProviders = `-- name: UpdateModelRouterInstallationExcludedProviders :execrows
UPDATE router.model_router_installations
SET excluded_providers = $1::text[],
    updated_at = NOW()
WHERE id = $2::uuid
  AND external_id = $3::varchar
  AND deleted_at IS NULL
  AND (NOT $4::boolean OR EXISTS (
    SELECT 1 FROM unnest($5::text[]) WITH ORDINALITY AS um(model, i)
    JOIN unnest($6::text[]) WITH ORDINALITY AS up(provider, i) ON up.i = um.i
    WHERE NOT (um.model = ANY(excluded_models))
      AND NOT (up.provider = ANY($1::text[]))
  ))
`

type UpdateModelRouterInstallationExcludedProvidersParams struct {
	ExcludedProviders []string
	ID                uuid.UUID
	ExternalID        string
	GuardRoutable     bool
	UniverseModels    []string
	UniverseProviders []string
}

// Replaces the per-installation provider exclusion list, scoped to an
// external_id to prevent cross-tenant updates. Empty array means "no
// exclusion". Bumps updated_at so dashboards see the change.
// Same guard_routable contract as UpdateModelRouterInstallationExcludedModels.
//
//	UPDATE router.model_router_installations
//	SET excluded_providers = $1::text[],
//	    updated_at = NOW()
//	WHERE id = $2::uuid
//	  AND external_id = $3::varchar
//	  AND deleted_at IS NULL
//	  AND (NOT $4::boolean OR EXISTS (
//	    SELECT 1 FROM unnest($5::text[]) WITH ORDINALITY AS um(model, i)
//	    JOIN unnest($6::text[]) WITH ORDINALITY AS up(provider, i) ON up.i = um.i
//	    WHERE NOT (um.model = ANY(excluded_models))
//	      AND NOT (up.provider = ANY($1::text[]))
//	  ))
func (q *Queries) UpdateModelRouterInstallationExcludedProviders(ctx context.Context, arg UpdateModelRouterInstallationExcludedProvidersParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateModelRouterInstallationExcludedProviders,
		arg.ExcludedProviders,
		arg.ID,
		arg.ExternalID,
		arg.GuardRoutable,
		arg.UniverseModels,
		arg.UniverseProviders,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateModelRouterInstallationFastModeModels = `-- name: UpdateModelRouterInstallationFastModeModels :execrows
UPDATE router.model_router_installations
SET fast_mode_models = $1::text[],
    updated_at = NOW()
WHERE id = $2::uuid
  AND external_id = $3::varchar
  AND deleted_at IS NULL
`

type UpdateModelRouterInstallationFastModeModelsParams struct {
	FastModeModels []string
	ID             uuid.UUID
	ExternalID     string
}

// Replaces the per-installation fast-mode opt-in list, scoped to an
// external_id to prevent cross-tenant updates. Listed models dispatch on the
// provider's fast tier; empty array means no model runs fast. Bumps updated_at
// so dashboards see the change.
//
//	UPDATE router.model_router_installations
//	SET fast_mode_models = $1::text[],
//	    updated_at = NOW()
//	WHERE id = $2::uuid
//	  AND external_id = $3::varchar
//	  AND deleted_at IS NULL
func (q *Queries) UpdateModelRouterInstallationFastModeModels(ctx context.Context, arg UpdateModelRouterInstallationFastModeModelsParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateModelRouterInstallationFastModeModels, arg.FastModeModels, arg.ID, arg.ExternalID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateModelRouterInstallationFlagOverrides = `-- name: UpdateModelRouterInstallationFlagOverrides :execrows
UPDATE router.model_router_installations
SET flag_overrides = $1::jsonb,
    updated_at = NOW()
WHERE id = $2::uuid
  AND external_id = $3::varchar
  AND deleted_at IS NULL
`

type UpdateModelRouterInstallationFlagOverridesParams struct {
	FlagOverrides []byte
	ID            uuid.UUID
	ExternalID    string
}

// Replaces the per-installation behavioral flag override set, scoped to an
// external_id to prevent cross-tenant updates. The payload is the whole sparse
// object, not a delta: callers read-modify-write so clearing an override is
// expressed by omitting its key. Keys are validated against internal/flags'
// registry before this runs. Bumps updated_at so dashboards see the change.
//
//	UPDATE router.model_router_installations
//	SET flag_overrides = $1::jsonb,
//	    updated_at = NOW()
//	WHERE id = $2::uuid
//	  AND external_id = $3::varchar
//	  AND deleted_at IS NULL
func (q *Queries) UpdateModelRouterInstallationFlagOverrides(ctx context.Context, arg UpdateModelRouterInstallationFlagOverridesParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateModelRouterInstallationFlagOverrides, arg.FlagOverrides, arg.ID, arg.ExternalID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateModelRouterInstallationHideTerminalSurfaces = `-- name: UpdateModelRouterInstallationHideTerminalSurfaces :execrows
UPDATE router.model_router_installations
SET hide_terminal_surfaces = $1::boolean,
    updated_at = NOW()
WHERE id = $2::uuid
  AND external_id = $3::varchar
  AND deleted_at IS NULL
`

type UpdateModelRouterInstallationHideTerminalSurfacesParams struct {
	HideTerminalSurfaces bool
	ID                   uuid.UUID
	ExternalID           string
}

// Toggles hiding the router's terminal surfaces (routing marker, feedback
// footer, statusline) for the installation, scoped to an external_id to
// prevent cross-tenant updates. Requests route identically; only what is
// rendered in the caller's terminal changes.
//
//	UPDATE router.model_router_installations
//	SET hide_terminal_surfaces = $1::boolean,
//	    updated_at = NOW()
//	WHERE id = $2::uuid
//	  AND external_id = $3::varchar
//	  AND deleted_at IS NULL
func (q *Queries) UpdateModelRouterInstallationHideTerminalSurfaces(ctx context.Context, arg UpdateModelRouterInstallationHideTerminalSurfacesParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateModelRouterInstallationHideTerminalSurfaces, arg.HideTerminalSurfaces, arg.ID, arg.ExternalID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateModelRouterInstallationPreferredModels = `-- name: UpdateModelRouterInstallationPreferredModels :execrows
UPDATE router.model_router_installations
SET preferred_models = $1::text[],
    updated_at = NOW()
WHERE id = $2::uuid
  AND external_id = $3::varchar
  AND deleted_at IS NULL
`

type UpdateModelRouterInstallationPreferredModelsParams struct {
	PreferredModels []string
	ID              uuid.UUID
	ExternalID      string
}

// Replaces the per-installation model priority ranking, scoped to an
// external_id to prevent cross-tenant updates. Empty array means no preference.
// Bumps updated_at so dashboards see the change.
//
//	UPDATE router.model_router_installations
//	SET preferred_models = $1::text[],
//	    updated_at = NOW()
//	WHERE id = $2::uuid
//	  AND external_id = $3::varchar
//	  AND deleted_at IS NULL
func (q *Queries) UpdateModelRouterInstallationPreferredModels(ctx context.Context, arg UpdateModelRouterInstallationPreferredModelsParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateModelRouterInstallationPreferredModels, arg.PreferredModels, arg.ID, arg.ExternalID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateModelRouterInstallationRoutingPreference = `-- name: UpdateModelRouterInstallationRoutingPreference :execrows
UPDATE router.model_router_installations
SET routing_quality_weight = $1,
    updated_at = NOW()
WHERE id = $2::uuid
  AND external_id = $3::varchar
  AND deleted_at IS NULL
`

type UpdateModelRouterInstallationRoutingPreferenceParams struct {
	RoutingQualityWeight *float64
	ID                   uuid.UUID
	ExternalID           string
}

// Sets the routing preference quality weight (a normalized fraction in [0, 1]),
// scoped to an external_id to prevent cross-tenant updates. NULL clears the
// preference so the scorer reverts to its tuned defaults.
//
//	UPDATE router.model_router_installations
//	SET routing_quality_weight = $1,
//	    updated_at = NOW()
//	WHERE id = $2::uuid
//	  AND external_id = $3::varchar
//	  AND deleted_at IS NULL
func (q *Queries) UpdateModelRouterInstallationRoutingPreference(ctx context.Context, arg UpdateModelRouterInstallationRoutingPreferenceParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateModelRouterInstallationRoutingPreference, arg.RoutingQualityWeight, arg.ID, arg.ExternalID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateModelRouterInstallationShowModelSelectionReasoning = `-- name: UpdateModelRouterInstallationShowModelSelectionReasoning :execrows
UPDATE router.model_router_installations
SET show_model_selection_reasoning = $1::boolean,
    updated_at = NOW()
WHERE id = $2::uuid
  AND external_id = $3::varchar
  AND deleted_at IS NULL
`

type UpdateModelRouterInstallationShowModelSelectionReasoningParams struct {
	ShowModelSelectionReasoning bool
	ID                          uuid.UUID
	ExternalID                  string
}

// Toggles the optional model-selection explanation shown alongside the routing
// marker. Scoped to the installation's external_id to prevent tenant crossover.
//
//	UPDATE router.model_router_installations
//	SET show_model_selection_reasoning = $1::boolean,
//	    updated_at = NOW()
//	WHERE id = $2::uuid
//	  AND external_id = $3::varchar
//	  AND deleted_at IS NULL
func (q *Queries) UpdateModelRouterInstallationShowModelSelectionReasoning(ctx context.Context, arg UpdateModelRouterInstallationShowModelSelectionReasoningParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateModelRouterInstallationShowModelSelectionReasoning, arg.ShowModelSelectionReasoning, arg.ID, arg.ExternalID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateModelRouterInstallationSubscriptionRoutingDisabled = `-- name: UpdateModelRouterInstallationSubscriptionRoutingDisabled :execrows
UPDATE router.model_router_installations
SET subscription_routing_disabled = $1::boolean,
    updated_at = NOW()
WHERE id = $2::uuid
  AND external_id = $3::varchar
  AND deleted_at IS NULL
`

type UpdateModelRouterInstallationSubscriptionRoutingDisabledParams struct {
	SubscriptionRoutingDisabled bool
	ID                          uuid.UUID
	ExternalID                  string
}

// Toggles subscription-aware routing for the installation, scoped to an
// external_id to prevent cross-tenant updates. When true, the scorer's
// subscription subsidy bonus is suppressed so routing decides on merits and
// non-Claude models compete fairly; the subscription credential is still
// forwarded for turns that route to Claude on their own merits.
//
//	UPDATE router.model_router_installations
//	SET subscription_routing_disabled = $1::boolean,
//	    updated_at = NOW()
//	WHERE id = $2::uuid
//	  AND external_id = $3::varchar
//	  AND deleted_at IS NULL
func (q *Queries) UpdateModelRouterInstallationSubscriptionRoutingDisabled(ctx context.Context, arg UpdateModelRouterInstallationSubscriptionRoutingDisabledParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateModelRouterInstallationSubscriptionRoutingDisabled, arg.SubscriptionRoutingDisabled, arg.ID, arg.ExternalID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateModelRouterInstallationUsageBypass = `-- name: UpdateModelRouterInstallationUsageBypass :execrows
UPDATE router.model_router_installations
SET usage_bypass_enabled = $1::boolean,
    usage_bypass_threshold = $2,
    updated_at = NOW()
WHERE id = $3::uuid
  AND external_id = $4::varchar
  AND deleted_at IS NULL
`

type UpdateModelRouterInstallationUsageBypassParams struct {
	UsageBypassEnabled   bool
	UsageBypassThreshold *float64
	ID                   uuid.UUID
	ExternalID           string
}

// Sets the subscription usage-bypass gate, scoped to an external_id to prevent
// cross-tenant updates. enabled toggles the gate; threshold is the [0, 1]
// utilization at/above which the gate disengages and normal routing takes over.
// A NULL threshold means "use the deployment default" at request time.
//
//	UPDATE router.model_router_installations
//	SET usage_bypass_enabled = $1::boolean,
//	    usage_bypass_threshold = $2,
//	    updated_at = NOW()
//	WHERE id = $3::uuid
//	  AND external_id = $4::varchar
//	  AND deleted_at IS NULL
func (q *Queries) UpdateModelRouterInstallationUsageBypass(ctx context.Context, arg UpdateModelRouterInstallationUsageBypassParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateModelRouterInstallationUsageBypass,
		arg.UsageBypassEnabled,
		arg.UsageBypassThreshold,
		arg.ID,
		arg.ExternalID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
