// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: task_domain_profiles.sql

package sqlc

import (
	"context"
)

const deleteExpiredTaskDomainProfiles = `-- name: DeleteExpiredTaskDomainProfiles :exec
DELETE FROM router.task_domain_profiles WHERE expires_at <= CURRENT_TIMESTAMP
`

// Expiry never grants permission to classify a compaction summary as an original task.
//
//	DELETE FROM router.task_domain_profiles WHERE expires_at <= CURRENT_TIMESTAMP
func (q *Queries) DeleteExpiredTaskDomainProfiles(ctx context.Context) error {
	_, err := q.db.Exec(ctx, deleteExpiredTaskDomainProfiles)
	return err
}

const getTaskDomainProfile = `-- name: GetTaskDomainProfile :one
SELECT outcome FROM router.task_domain_profiles
WHERE conversation_key = $1::text AND root_sha256 = $2::text
AND release_sha256 = $3::text AND evidence_sha256 = $4::text
AND expires_at > CURRENT_TIMESTAMP AND outcome IS NOT NULL
AND (retry_after IS NULL OR retry_after > CURRENT_TIMESTAMP)
`

type GetTaskDomainProfileParams struct {
	ConversationKey string
	RootSha256      string
	ReleaseSha256   string
	EvidenceSha256  string
}

// Completed profiles never wait behind unrelated first-turn inference transactions.
// A failure past its retry window is a miss, so the caller reclassifies.
//
//	SELECT outcome FROM router.task_domain_profiles
//	WHERE conversation_key = $1::text AND root_sha256 = $2::text
//	AND release_sha256 = $3::text AND evidence_sha256 = $4::text
//	AND expires_at > CURRENT_TIMESTAMP AND outcome IS NOT NULL
//	AND (retry_after IS NULL OR retry_after > CURRENT_TIMESTAMP)
func (q *Queries) GetTaskDomainProfile(ctx context.Context, arg GetTaskDomainProfileParams) ([]byte, error) {
	row := q.db.QueryRow(ctx, getTaskDomainProfile,
		arg.ConversationKey,
		arg.RootSha256,
		arg.ReleaseSha256,
		arg.EvidenceSha256,
	)
	var outcome []byte
	err := row.Scan(&outcome)
	return outcome, err
}

const getTaskDomainProfileForUpdate = `-- name: GetTaskDomainProfileForUpdate :one
SELECT outcome FROM router.task_domain_profiles
WHERE conversation_key = $1::text AND root_sha256 = $2::text
AND release_sha256 = $3::text AND evidence_sha256 = $4::text
AND expires_at > CURRENT_TIMESTAMP
FOR UPDATE
`

type GetTaskDomainProfileForUpdateParams struct {
	ConversationKey string
	RootSha256      string
	ReleaseSha256   string
	EvidenceSha256  string
}

// The row lock spans only the bounded first classification and content-free commit.
//
//	SELECT outcome FROM router.task_domain_profiles
//	WHERE conversation_key = $1::text AND root_sha256 = $2::text
//	AND release_sha256 = $3::text AND evidence_sha256 = $4::text
//	AND expires_at > CURRENT_TIMESTAMP
//	FOR UPDATE
func (q *Queries) GetTaskDomainProfileForUpdate(ctx context.Context, arg GetTaskDomainProfileForUpdateParams) ([]byte, error) {
	row := q.db.QueryRow(ctx, getTaskDomainProfileForUpdate,
		arg.ConversationKey,
		arg.RootSha256,
		arg.ReleaseSha256,
		arg.EvidenceSha256,
	)
	var outcome []byte
	err := row.Scan(&outcome)
	return outcome, err
}

const getTaskDomainResumeProfiles = `-- name: GetTaskDomainResumeProfiles :many
SELECT outcome FROM router.task_domain_profiles
WHERE conversation_key = $1::text AND release_sha256 = $2::text
AND evidence_sha256 = $3::text AND expires_at > CURRENT_TIMESTAMP
LIMIT 2
`

type GetTaskDomainResumeProfilesParams struct {
	ConversationKey string
	ReleaseSha256   string
	EvidenceSha256  string
}

// A compacted conversation may recover only one unambiguous task root.
//
//	SELECT outcome FROM router.task_domain_profiles
//	WHERE conversation_key = $1::text AND release_sha256 = $2::text
//	AND evidence_sha256 = $3::text AND expires_at > CURRENT_TIMESTAMP
//	LIMIT 2
func (q *Queries) GetTaskDomainResumeProfiles(ctx context.Context, arg GetTaskDomainResumeProfilesParams) ([][]byte, error) {
	rows, err := q.db.Query(ctx, getTaskDomainResumeProfiles, arg.ConversationKey, arg.ReleaseSha256, arg.EvidenceSha256)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items [][]byte
	for rows.Next() {
		var outcome []byte
		if err := rows.Scan(&outcome); err != nil {
			return nil, err
		}
		items = append(items, outcome)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertTaskDomainProfile = `-- name: InsertTaskDomainProfile :exec
INSERT INTO router.task_domain_profiles (conversation_key, root_sha256, release_sha256, evidence_sha256)
VALUES ($1::text, $2::text, $3::text, $4::text)
ON CONFLICT (conversation_key, root_sha256, release_sha256, evidence_sha256)
DO UPDATE SET outcome = NULL, retry_after = NULL, expires_at = CURRENT_TIMESTAMP + INTERVAL '30 days'
WHERE task_domain_profiles.expires_at <= CURRENT_TIMESTAMP
OR task_domain_profiles.retry_after <= CURRENT_TIMESTAMP
`

type InsertTaskDomainProfileParams struct {
	ConversationKey string
	RootSha256      string
	ReleaseSha256   string
	EvidenceSha256  string
}

// Reserve a root before acquiring its cross-replica inference lock. An expired row, or a
// failure whose retry window has passed, is reset for a fresh classification.
//
//	INSERT INTO router.task_domain_profiles (conversation_key, root_sha256, release_sha256, evidence_sha256)
//	VALUES ($1::text, $2::text, $3::text, $4::text)
//	ON CONFLICT (conversation_key, root_sha256, release_sha256, evidence_sha256)
//	DO UPDATE SET outcome = NULL, retry_after = NULL, expires_at = CURRENT_TIMESTAMP + INTERVAL '30 days'
//	WHERE task_domain_profiles.expires_at <= CURRENT_TIMESTAMP
//	OR task_domain_profiles.retry_after <= CURRENT_TIMESTAMP
func (q *Queries) InsertTaskDomainProfile(ctx context.Context, arg InsertTaskDomainProfileParams) error {
	_, err := q.db.Exec(ctx, insertTaskDomainProfile,
		arg.ConversationKey,
		arg.RootSha256,
		arg.ReleaseSha256,
		arg.EvidenceSha256,
	)
	return err
}

const updateTaskDomainProfile = `-- name: UpdateTaskDomainProfile :exec
UPDATE router.task_domain_profiles SET outcome = $1::jsonb,
    retry_after = CASE WHEN $2::boolean THEN CURRENT_TIMESTAMP + INTERVAL '5 minutes' END
WHERE conversation_key = $3::text AND root_sha256 = $4::text
AND release_sha256 = $5::text AND evidence_sha256 = $6::text
`

type UpdateTaskDomainProfileParams struct {
	Outcome         []byte
	Failed          bool
	ConversationKey string
	RootSha256      string
	ReleaseSha256   string
	EvidenceSha256  string
}

// Persist outcomes without prompt text. A failed classification becomes retryable after
// five minutes, at most once per window, instead of keeping the task on baseline ranking
// for the 30-day profile lifetime. The row itself keeps that lifetime so it still counts
// toward resume ambiguity.
//
//	UPDATE router.task_domain_profiles SET outcome = $1::jsonb,
//	    retry_after = CASE WHEN $2::boolean THEN CURRENT_TIMESTAMP + INTERVAL '5 minutes' END
//	WHERE conversation_key = $3::text AND root_sha256 = $4::text
//	AND release_sha256 = $5::text AND evidence_sha256 = $6::text
func (q *Queries) UpdateTaskDomainProfile(ctx context.Context, arg UpdateTaskDomainProfileParams) error {
	_, err := q.db.Exec(ctx, updateTaskDomainProfile,
		arg.Outcome,
		arg.Failed,
		arg.ConversationKey,
		arg.RootSha256,
		arg.ReleaseSha256,
		arg.EvidenceSha256,
	)
	return err
}
