# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: Weave Checks

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  weave-checks:
    if: github.event.pull_request.head.repo.full_name == github.repository
    uses: weave-os/checks/.github/workflows/weave-checks.yml@38f84fa049d33e50da5fc4e81da5e6e656bad484 # v1.0
    permissions:
      id-token: write
    with:
      use-default-checks: true
    secrets:
      weave-router-key: ${{ secrets.WEAVE_ROUTER_KEY }}
